AWSTemplateFormatVersion: 2010-09-09

Resources:
  HalifaxFoodPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      UserPoolName: halifax-food-pool-prod
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: userType
          AttributeDataType: String
          Mutable: true
          Required: false

  HalifaxFoodPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref HalifaxFoodPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:3000
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO

  HalifaxFoodPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: "halifax-food-prod"
      UserPoolId: !Ref HalifaxFoodPool